apiVersion: v1
kind: Service
metadata:
  name: nginx-log-exporter
  namespace: social-network
  labels:
    app: nginx-thrift
    component: nginx-log-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "4040"
    prometheus.io/path: "/metrics"
spec:
  selector:
    service: nginx-thrift
  ports:
  - name: metrics
    port: 4040
    targetPort: 4040
    protocol: TCP
